### PR TITLE
handle `codeloc==0` in `linenumber`

### PR DESCRIPTION
**Pull request by pfitzseb**
Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/63.

### CODE REVIEW

**Comment by KristofferC** [comment]
Would `return nothing` here be more "julian" in some way?

**Comment by pfitzseb** [comment]
Yup, unless you know how to make the printing prettier? :)

**Comment by KristofferC** [comment]
🤷‍♂️ why not, let's try that. Feels a bit less C-y :P

**Comment by pfitzseb** [comment]
Done.

**Pull request merged**
