### PR TITLE
yet more minor code quality improvement

### PR DESCRIPTION
**Pull request by aviatesk**

### CODE REVIEW

**Review by timholy — APPROVED** [review]

**Comment by aviatesk** [comment]
@timholy do you mind if I merge this PR by myself ? I'm happy to take responsibilities for these changes if I have a write access to this repository.

**Comment by KristofferC** [comment]
Yeah, I added you as a collaborator.

**Comment by timholy** [comment]
Some time ago I added you to JuliaDebug, so you should be able to merge to any of the repos in that organization.

**Comment by aviatesk** [comment]
yeah I was added to JuliaDebug, but it seems that the default permission doesn't include write access and so I only have write access to LoweredCodeUtils.jl and JuliaInterpreter.jl for now.
(I guess we need to configure [base permissions](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/setting-base-permissions-for-an-organization) for the organization if we want to give default write access to the repositories, but I'm not especially for the other repos like Cthulhu.jl or Infiltrator.jl for now, so just for your information.)

Thanks @KristofferC for adding me as collaborator.

**Pull request merged**
