### PR TITLE
Try harder to unwrap UnionAlls

### PR DESCRIPTION
**Pull request by pfitzseb**
This fixes the issue reported [here](https://github.com/julia-vscode/julia-vscode/issues/1693#issuecomment-781377955):
```
shell> cat test.csv
StartDate,Q2_Id
Start Date,"Please upload your savefile if you can - it'll be named something like __InterceptionXX.gz. You'll find it at:

Documents\My Games\Wesnoth\saves\ on Windows,or

~/.local/share/wesnoth//saves/ on Linux - ID"
2020-08-23 04:52:09,
2020-08-23 05:08:02,
2020-08-23 10:06:36,F_3smplS6AiQMH7Gy
julia> using CSV

julia> @interpret CSV.File("test.csv")
ERROR: TypeError: in typeassert, expected DataType, got Type{Array{T,N} where N}
Stacktrace:
 [1] parametric_type_to_expr(::Type) at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/optimize.jl:251
 [2] build_compiled_call!(::Expr, ::Symbol, ::Core.CodeInfo, ::Int64, ::Int64, ::Array{Symbol,1}, ::Module) at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/optimize.jl:342
 [3] optimize!(::Core.CodeInfo, ::Method) at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/optimize.jl:192
 [4] JuliaInterpreter.FrameCode(::Method, ::Core.CodeInfo; generator::Bool, optimize::Bool) at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/types.jl:101
 [5] prepare_framecode(::Method, ::Any; enter_generated::Bool) at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/construct.jl:190
 [6] prepare_call(::Any, ::Array{Any,1}; enter_generated::Bool) at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/construct.jl:261
 [7] get_call_framecode(::Array{Any,1}, ::JuliaInterpreter.FrameCode, ::Int64; enter_generated::Bool) at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/localmethtable.jl:63
 [8] evaluate_call_recurse!(::Any, ::Frame, ::Expr; enter_generated::Bool) at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/interpret.jl:224
 [9] evaluate_call_recurse! at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/interpret.jl:201 [inlined]
 [10] eval_rhs(::Any, ::Frame, ::Expr) at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/interpret.jl:394
 [11] step_expr!(::Any, ::Frame, ::Any, ::Bool) at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/interpret.jl:537
 [12] step_expr! at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/interpret.jl:587 [inlined]
 [13] finish!(::Any, ::Frame, ::Bool) at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/commands.jl:14
 [14] finish_and_return! at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/commands.jl:29 [inlined]
 [15] evaluate_call_recurse!(::Any, ::Frame, ::Expr; enter_generated::Bool) at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/interpret.jl:239
 ... (the last 7 lines are repeated 2 more times)
 [30] evaluate_call_recurse! at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/interpret.jl:201 [inlined]
 [31] eval_rhs(::Any, ::Frame, ::Expr) at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/interpret.jl:394
 [32] step_expr!(::Any, ::Frame, ::Any, ::Bool) at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/interpret.jl:450
 [33] step_expr! at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/interpret.jl:587 [inlined]
 [34] finish!(::Any, ::Frame, ::Bool) at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/commands.jl:14
 [35] finish_and_return! at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/commands.jl:29 [inlined]
 [36] evaluate_call_recurse!(::Any, ::Frame, ::Expr; enter_generated::Bool) at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/interpret.jl:239
 [37] evaluate_call_recurse! at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/interpret.jl:201 [inlined]
 [38] eval_rhs(::Any, ::Frame, ::Expr) at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/interpret.jl:394
 [39] step_expr!(::Any, ::Frame, ::Any, ::Bool) at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/interpret.jl:537
 ... (the last 7 lines are repeated 3 more times)
 [61] step_expr! at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/interpret.jl:587 [inlined]
 [62] finish!(::Any, ::Frame, ::Bool) at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/commands.jl:14
 [63] finish_and_return! at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/commands.jl:29 [inlined]
 [64] finish_and_return! at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/commands.jl:33 [inlined] (repeats 2 times)
```

Not entirely sure how to get a MWE from there, so I haven't added a test.

### CODE REVIEW

**Review by aviatesk — APPROVED** [review]
LGTM. CI failures seem unrelated.

**Comment by timholy** [comment]
> Not entirely sure how to get a MWE from there, so I haven't added a test.

An easy way to get a MWE (I do this all the time, I think about it as an "error capture"):
1. temporarily back out your change so that you are restoring the error
2. add a `@show t` at the top of the function from which the error is thrown (`parametric_type_to_expr` in your case). See below for "tricky cases"
3. Run the complicated thing that eventually triggers the error. The last-printed `t = blah blah` should be the `t` that caused the error
4. try that `t` directly as an argument to `parametric_type_to_expr` & verify you get the error
5. add as a test and make sure you trigger the error when you run the tests
6. re-enable your change fixing the error and submit PR

Tricky cases: sometimes display isn't ideal: either it doesn't convey enough information about the offensive object to recreate it, or it's too large, or something. In such cases I use this pattern:

```julia
const lastargs = Ref{Any}(nothing)
function brokenfunction(args...; kwargs...)
    lastargs[] = (args, kwargs)
    # now the broken code
end
```

Now run the function from the REPL and do
```
args, kwargs = BrokenPkg.lastargs[]
```
to retrieve the arguments that were passed that trigger the error. Then you can probe them in much more flexible ways than `@show` permits. Obviously, back all this error-trap code out once you have both the test & fix in place.

All this is quick and easy with Revise.

**Comment by pfitzseb** [comment]
Ok, now I fell kinda stupid. I was thinking in terms of integration tests the whole time -- I'd actually followed exactly that procedure to figure out the bug. Well, bang-head-against-wall-moment for me, but thanks for taking the time to detail your workflow!

**Comment by timholy** [comment]
No worries, it's admirable to want an integration test and I sort of guessed that might be what you were after. Obviously that would be even better, but in general I think some test is better than none.

In this particular case `parametric_type_to_expr` is not such a weird function that it doesn't merit a standalone test, so it's great to have your addition.

You've just replicated `Base.unwrap_unionall` but that seems fine, esp. given that we weren't using it before.

**Comment by pfitzseb** [comment]
Yeah, so the reason why I wasn't using `Base.unwrap_unionall` is that I got this while testing:
```
julia> Base.unwrap_unionall(Array)
TypeError(:new, "", UnionAll, Array{T,N})
```
which is, I think, a bug in the VSCode REPL.

**Pull request merged**
