### PR TITLE
Support CodeTracking 0.5

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by timholy** [comment]
Not sure if there's a different strategy we want to use for these compat issues, happy to accept guidance.

**Comment by timholy** [comment]
Hmm, on Travis it's installing CodeTracking 0.3.2. Why?

**Comment by KristofferC** [comment]
Because https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/c3854f57fbedf65b16b788ab12a7f41c9d0f1230/Manifest.toml#L10.

I don't see a better way than this (and I don't think the current way is bad). If a dependency releases a breaking version, we have to test that we are compatible and then add a line saying that we are.

**Comment by timholy** [comment]
Why can't we just delete that Manifest now? For anyone who `add`s this, they won't even reference it.

**Comment by KristofferC** [comment]
We can delete it. It's just up to us to decide if we want to test things on fixed versions or the versions the resolver happens to give us when CI is run.

**Comment by timholy** [comment]
I think it's better to test what the majority of users will test.

**Pull request merged**
