### PR TITLE
Step through preparation for kwarg calls

### PR DESCRIPTION
**Pull request by timholy**
I am tired of stepping through `NamedTuple`, `pairs`, `merge`, and `Core.kwfunc`. This feels better.

### CODE REVIEW

**Comment by KristofferC** [comment]
Great! A related question, should we also step "out" of wrappers, e.g.

```

**Comment by pfitzseb** [comment]
Yes please :) Although there probably should be some way to inspect all wrappers etc.

**Comment by KristofferC** [comment]
I guess it can also be up to the frontend to call `maybe_step_through_wrapper!` and remember if it was a wrapper and in that case `finish!` the frame when it becomes active again.

**Comment by timholy** [comment]
You can definitely do fine-grained stuff with `se` and `si`. Since this doesn't change frames at all, stepping out of wrappers is a bit orthogonal to this particular PR.

But I'd be fine with moving the magic out of `debug_command`. Is that the consensus? Vote thumbs-up or thumbs-down.

**Comment by KristofferC** [comment]
Personally, I don't mind since I would likely be using this myself. It is just in the situation where one does not want the automatic wrapper stepping, one would have to reconstruct `s` and co based on `si` then?

**Comment by timholy** [comment]
Yes, `si` should avoid the wrapper-stepping. To me that seems like a reasonable solution.

**Comment by timholy** [comment]
Test failures seem spurious, so if we decide we like this we could merge. Want to make the call, @KristofferC?

**Comment by KristofferC** [comment]
> Yes, si should avoid the wrapper-stepping.

Yes, but it also doesn't step to the next caller. But sure, someone can do

```
function s_without_step_through(frame)
    while true
        ret = si(frame)
        ret = nothing && ...
        new_frame, pc = ret
        frame !== new_frame && return new_frame
    end
end
```

**Pull request merged**
