### PR TITLE
always use QuoteNode in eval_code

### PR DESCRIPTION
**Pull request by simeonschaub**
This fixes a pretty nasty segfault in Debugger.jl for me (see https://gist.github.com/simeonschaub/33313623fd14ecbaa147b6e77946154c). @KristofferC Was there a particular reason for introducing `maybe_quote` here and not just quote everything in a QuoteNode?

### CODE REVIEW

**Comment by KristofferC** [comment]
>  Was there a particular reason for introducing maybe_quote here and not just quote everything in a QuoteNode?

I think it was just carried over from the old ASTInterpreter, but not sure. No particular reason from what I recall, at least.

**Review by timholy — APPROVED** [review]
Thanks for the test case, too!

**Comment by simeonschaub** [comment]
Opened an issue for the failing test cases: #470. These were failing before as well, so not related to this PR.

Ok if I bump the patch version and tag a new release right away?

**Comment by timholy** [comment]
That would be great.

**Pull request merged**
