### PR TITLE
re-automate builtins generations

### PR DESCRIPTION
**Pull request by aviatesk**
Now JuliaInterpreter will automatically pick up the latest compatible
builtins file under `src/builtins` and `include` it (with the fallback
`0.0.0` file freeze at #449).
So with this PR we no longer need to manually update builtin files under
within `src`, and can focus on just updating `bin/generate_builtins.jl`
on future changes in Julia.

What we lose with this PR is, updating already generated files later can 
be tedious; say if we have 10 more generated files under `src/builtins` 
in the future, and then manually applying something like #442 to all of 
them can be really annoying..

NOTE: to check the CI results, this PR is built on #449, so please review this after #449

### CODE REVIEW

**Comment by aviatesk** [comment]
Just for reference, here is the diff between `src/builtins/0.0.0` (our current builtins.jl) and `src/builtins/1.7.0-DEV.76` (the newly generated file):

> git diff --no-index src/builtins/0.0.0 src/builtins/1.7.0-DEV.76
```diff
diff --git a/src/builtins/0.0.0 b/src/builtins/1.7.0-DEV.76
index 54edd5d..6edfb67 100644
--- a/src/builtins/0.0.0
+++ b/src/builtins/1.7.0-DEV.76
@@ -1,6 +1,5 @@
-# This file is mostly generated by `generate_builtins.jl` with some additional @static checks
-# for recently added builtins.
-# This file is used as the fallback file for Julia versions before 1.7.0-DEV.76.
+# This file is generated by `generate_builtins.jl`. Do not edit by hand.
+# This file will be used for Julia version 1.7.0-DEV.76 or higher if there is no other latest builtins files.
 
 function getargs(args, frame)
     nargs = length(args)-1  # skip f
@@ -52,6 +51,8 @@ function maybe_evaluate_builtin(frame, call_expr, expand::Bool)
         else
             return Some{Any}(===(getargs(args, frame)...))
         end
+    elseif f === Core._abstracttype
+        return Some{Any}(Core._abstracttype(getargs(args, frame)...))
     elseif f === Core._apply
         argswrapped = getargs(args, frame)
         if !expand
@@ -64,22 +65,28 @@ function maybe_evaluate_builtin(frame, call_expr, expand::Bool)
             push!(new_expr.args, (isa(x, Symbol) || isa(x, Expr) || isa(x, QuoteNode)) ? QuoteNode(x) : x)
         end
         return new_expr
-    elseif @static isdefined(Core, :_call_latest) ? f === Core._call_latest : false
+    elseif f === Core._apply_iterate
         argswrapped = getargs(args, frame)
         if !expand
-            return Some{Any}(Core._call_latest(argswrapped...))
+            return Some{Any}(Core._apply_iterate(argswrapped...))
         end
-        new_expr = Expr(:call, argswrapped[1])
-        popfirst!(argswrapped)
-        argsflat = append_any(argswrapped...)
+        aw1 = argswrapped[1]::Function
+        @assert aw1 === Core.iterate || aw1 === Core.Compiler.iterate || aw1 === Base.iterate "cannot handle `_apply_iterate` with non iterate as first argument, got $(aw1), $(typeof(aw1))"
+        new_expr = Expr(:call, argswrapped[2])
+        popfirst!(argswrapped) # pop the iterate
+        popfirst!(argswrapped) # pop the function
         for x in argsflat
             push!(new_expr.args, (isa(x, Symbol) || isa(x, Expr) || isa(x, QuoteNode)) ? QuoteNode(x) : x)
         end
         return new_expr
-    elseif @static isdefined(Core, :_apply_latest) ? f === Core._apply_latest : false
+    elseif f === Core._apply_pure
+        return Some{Any}(Core._apply_pure(getargs(args, frame)...))
+    elseif f === Core._call_in_world
+        return Some{Any}(Core._call_in_world(getargs(args, frame)...))
+    elseif f === Core._call_latest
         argswrapped = getargs(args, frame)
         if !expand
-            return Some{Any}(Core._apply_latest(argswrapped...))
+            return Some{Any}(Core._call_latest(argswrapped...))
         end
         new_expr = Expr(:call, argswrapped[1])
         popfirst!(argswrapped)
@@ -88,41 +95,28 @@ function maybe_evaluate_builtin(frame, call_expr, expand::Bool)
             push!(new_expr.args, (isa(x, Symbol) || isa(x, Expr) || isa(x, QuoteNode)) ? QuoteNode(x) : x)
         end
         return new_expr
-    elseif @static isdefined(Core, :_apply_iterate) ? f === Core._apply_iterate : false
-        argswrapped = getargs(args, frame)
-        if !expand
-            return Some{Any}(Core._apply_iterate(argswrapped...))
-        end
-        aw1 = argswrapped[1]::Function
-        @assert aw1 === Core.iterate || aw1 === Core.Compiler.iterate || aw1 === Base.iterate "cannot handle `_apply_iterate` with non iterate as first argument, got $(aw1), $(typeof(aw1))"
-        new_expr = Expr(:call, argswrapped[2])
-        popfirst!(argswrapped) # pop the iterate
-        popfirst!(argswrapped) # pop the function
-        argsflat = append_any(argswrapped...)
-        for x in argsflat
-            push!(new_expr.args, (isa(x, Symbol) || isa(x, Expr) || isa(x, QuoteNode)) ? QuoteNode(x) : x)
-        end
-        return new_expr
-    elseif f === Core._apply_pure
-        return Some{Any}(Core._apply_pure(getargs(args, frame)...))
+    elseif f === Core._equiv_typedef
+        return Some{Any}(Core._equiv_typedef(getargs(args, frame)...))
     elseif f === Core._expr
         return Some{Any}(Core._expr(getargs(args, frame)...))
-    elseif @static isdefined(Core, :_typevar) ? f === Core._typevar : false
-        if nargs == 3
-            return Some{Any}(Core._typevar(@lookup(frame, args[2]), @lookup(frame, args[3]), @lookup(frame, args[4])))
-        else
-            return Some{Any}(Core._typevar(getargs(args, frame)...))
-        end
+    elseif f === Core._primitivetype
+        return Some{Any}(Core._primitivetype(getargs(args, frame)...))
+    elseif f === Core._setsuper!
+        return Some{Any}(Core._setsuper!(getargs(args, frame)...))
+    elseif f === Core._structtype
+        return Some{Any}(Core._structtype(getargs(args, frame)...))
+    elseif f === Core._typebody!
+        return Some{Any}(Core._typebody!(getargs(args, frame)...))
+    elseif f === Core._typevar
+            if nargs == 3
+                return Some{Any}(Core._typevar(@lookup(frame, args[2]), @lookup(frame, args[3]), @lookup(frame, args[4])))
+            else
+                return Some{Any}(Core._typevar(getargs(args, frame)...))
+            end
     elseif f === Core.apply_type
         return Some{Any}(Core.apply_type(getargs(args, frame)...))
     elseif f === Core.arrayref
-        if nargs == 0
-            return Some{Any}(Core.arrayref())
-        elseif nargs == 1
-            return Some{Any}(Core.arrayref(@lookup(frame, args[2])))
-        elseif nargs == 2
-            return Some{Any}(Core.arrayref(@lookup(frame, args[2]), @lookup(frame, args[3])))
-        elseif nargs == 3
+        if nargs == 3
             return Some{Any}(Core.arrayref(@lookup(frame, args[2]), @lookup(frame, args[3]), @lookup(frame, args[4])))
         elseif nargs == 4
             return Some{Any}(Core.arrayref(@lookup(frame, args[2]), @lookup(frame, args[3]), @lookup(frame, args[4]), @lookup(frame, args[5])))
@@ -132,15 +126,7 @@ function maybe_evaluate_builtin(frame, call_expr, expand::Bool)
             return Some{Any}(Core.arrayref(getargs(args, frame)...))
         end
     elseif f === Core.arrayset
-        if nargs == 0
-            return Some{Any}(Core.arrayset())
-        elseif nargs == 1
-            return Some{Any}(Core.arrayset(@lookup(frame, args[2])))
-        elseif nargs == 2
-            return Some{Any}(Core.arrayset(@lookup(frame, args[2]), @lookup(frame, args[3])))
-        elseif nargs == 3
-            return Some{Any}(Core.arrayset(@lookup(frame, args[2]), @lookup(frame, args[3]), @lookup(frame, args[4])))
-        elseif nargs == 4
+        if nargs == 4
             return Some{Any}(Core.arrayset(@lookup(frame, args[2]), @lookup(frame, args[3]), @lookup(frame, args[4]), @lookup(frame, args[5])))
         elseif nargs == 5
             return Some{Any}(Core.arrayset(@lookup(frame, args[2]), @lookup(frame, args[3]), @lookup(frame, args[4]), @lookup(frame, args[5]), @lookup(frame, args[6])))
@@ -155,7 +141,7 @@ function maybe_evaluate_builtin(frame, call_expr, expand::Bool)
         else
             return Some{Any}(Core.arraysize(getargs(args, frame)...))
         end
-    elseif @static isdefined(Core, :const_arrayref) ? f === Core.const_arrayref : false
+    elseif f === Core.const_arrayref
         return Some{Any}(Core.const_arrayref(getargs(args, frame)...))
     elseif f === Core.sizeof
         if nargs == 1
@@ -202,9 +188,7 @@ function maybe_evaluate_builtin(frame, call_expr, expand::Bool)
             return Some{Any}(isa(getargs(args, frame)...))
         end
     elseif f === isdefined
-        if nargs == 1
-            return Some{Any}(isdefined(@lookup(frame, args[2])))
-        elseif nargs == 2
+        if nargs == 2
             return Some{Any}(isdefined(@lookup(frame, args[2]), @lookup(frame, args[3])))
         else
             return Some{Any}(isdefined(getargs(args, frame)...))
@@ -228,7 +212,7 @@ function maybe_evaluate_builtin(frame, call_expr, expand::Bool)
             return Some{Any}(throw(getargs(args, frame)...))
         end
     elseif f === tuple
-        return Some{Any}(ntupleany(i->@lookup(frame, args[i+1]), length(args)-1))
+        return Some{Any}(ntuple(i->@lookup(frame, args[i+1]), length(args)-1))
     elseif f === typeassert
         if nargs == 2
             return Some{Any}(typeassert(@lookup(frame, args[2]), @lookup(frame, args[3])))
@@ -250,8 +234,8 @@ function maybe_evaluate_builtin(frame, call_expr, expand::Bool)
             call_expr.args[3] = @lookup(frame, args[3])
             return Some{Any}(Core.eval(moduleof(frame), call_expr))
         end
-    elseif f === Base.llvmcall
-        return Some{Any}(Base.llvmcall(getargs(args, frame)...))
+    elseif f === Core.Intrinsics.llvmcall
+        return Some{Any}(Core.Intrinsics.llvmcall(getargs(args, frame)...))
     end
     if isa(f, Core.IntrinsicFunction)
         cargs = getargs(args, frame)
```

**Comment by aviatesk** [comment]
Oh no, https://github.com/JuliaLang/julia/pull/38136 is quite breaking for this package, the nightlies will break until we follow up that.

**Review by timholy — APPROVED** [review]
I think @KristofferC was the one who turned this off, likely for good reason, so I'll defer to his judgement here. But all this looks excellent, so regardless of whether we adopt it, nice work as always!

**Comment by KristofferC** [comment]
The previous auto-generation generated the file itself during either build time or precompile time at the local computer, it wasn't checked in. This was kinda annoying because you had to turn off this auto generation when you wanted to debug the builtins file and you couldn't e.g. link to lines in it in the repo (since the file wasn't there).

At the same time, checking in a bunch of almost equal auto-generated files also feels non-ideal. Personally, I thought the manual update with version checks was fine but if people feel they rather check in a full builtin file for every commit that changes the builtins in Julia, I that's ok as well.

**Comment by timholy** [comment]
The most important thing I can say is that I'm fine with any option.

**Comment by aviatesk** [comment]
> At the same time, checking in a bunch of almost equal auto-generated files also feels non-ideal.

Fair point.
Now I feel the approach of this PR may be worse than the current state. I guess:
- it may not even clear when to create a new `src/builtins/newbuiltins.jl`, and which version it should have
- it may be possible we need to manually update already-generated files later on (e.g. when we found a problem within `generate_builtins.jl`)

So let me close this ! Sorry for the noise, but now I understand why we aren't using the `generate_builtins.jl`, at least :)

**Pull request closed without merging**
