### PR TITLE
compat with Julia 1.x

### PR DESCRIPTION
**Pull request by pfitzseb**

### CODE REVIEW

**Comment by timholy** [comment]
Wow, that was easier than expected. I know this was painful at one point, but maybe other improvements to the code made it more robust.

**Comment by pfitzseb** [comment]
Yeah. There's still this super weird filename issue on Windows and Julia 1.2 I'm trying to understand...

**Comment by timholy** [comment]
Looks like a compiler error.

**Comment by pfitzseb** [comment]
Alright, added an ugly workaround for 1.2 and completely moved us to GitHub Actions.

**Review by KristofferC — APPROVED** [review]
Nice! Thanks for the Github Action movement. I deleted the AppVeyor integration.

**Review by aviatesk — APPROVED** [review]
Thanks Sebastian for doing this ;)

**Pull request merged**
