### PR TITLE
global breakpoints

### PR DESCRIPTION
**Pull request by pfitzseb**
Seems to work fine afaict, but still needs tests.

Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/368.

### CODE REVIEW

**Comment by KristofferC** [comment]
Implementation looks good to me.

**Comment by timholy** [comment]
Looks good. Without trying it I'm not sure what's causing the failure on 1.0.

**Comment by pfitzseb** [comment]
Turns out there's [no line number node for the first line on Julia 1.0/1.1](https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/f4316aeb338b7cc666ec6bc7351a428ca82194e5/src/construct.jl#L420):
```
julia> expr = Base.parse_input_line(expr, filename = "foo.jl")
:($(Expr(:toplevel, :(1 + 1), quote
    #= foo.jl:3 =#
    2 + 2
    #= foo.jl:4 =#
    3 + 3
...
```
vs
```
julia> expr = Base.parse_input_line(expr, filename = "foo.jl")
:($(Expr(:toplevel, :(#= foo.jl:1 =#), :(1 + 1), :(#= line 2 =#), quote
    #= foo.jl:3 =#
    2 + 2
    #= foo.jl:4 =#
    3 + 3
...
```

Not sure what we can do about that though -- maybe insert a new LNN for the first line or something?

**Comment by KristofferC** [comment]
Imo no need to put too much effort into it. I would just make it as `@test_broken` on it.

**Comment by pfitzseb** [comment]
Done.

**Comment by KristofferC** [comment]
Exciting new errors on master, doesn't have to be dealt with here of course.

**Comment by timholy** [comment]
Thanks a ton, @pfitzseb!

**Pull request merged**
