### PR TITLE
Don't splat in call to `append_any`

### PR DESCRIPTION
**Pull request by timholy**
Fixes https://github.com/timholy/Revise.jl/issues/625

### CODE REVIEW

**Comment by timholy** [comment]
Here's the full stacktrace on `master` with a `@show argswrapped` right before the call to `append_any`:

```
argswrapped = Any[Main.ForInclude, "dummy_file.jl"]
include: Error During Test at REPL[4]:3
  Test threw exception
  Expression: JuliaInterpreter.finish_and_return!(Frame(ForInclude, ex), true) == 55
  MethodError: no method matching iterate(::Module)
  Closest candidates are:
    iterate(::Union{LinRange, StepRangeLen}) at range.jl:664
    iterate(::Union{LinRange, StepRangeLen}, ::Int64) at range.jl:664
    iterate(::T) where T<:Union{Base.KeySet{var"#s79", var"#s78"} where {var"#s79", var"#s78"<:Dict}, Base.ValueIterator{var"#s77"} where var"#s77"<:Dict} at dict.jl:693
    ...
  Stacktrace:
    [1] append_any(::Any, ::Vararg{Any, N} where N)
      @ JuliaInterpreter ~/.julia/dev/JuliaInterpreter/src/packagedef.jl:31
    [2] maybe_evaluate_builtin(frame::Frame, call_expr::Expr, expand::Bool)
      @ JuliaInterpreter ~/.julia/dev/JuliaInterpreter/src/builtins.jl:74
    [3] evaluate_call_recurse!(recurse::Any, frame::Frame, call_expr::Expr; enter_generated::Bool)
      @ JuliaInterpreter ~/.julia/dev/JuliaInterpreter/src/interpret.jl:204
    [4] evaluate_call_recurse!
      @ ~/.julia/dev/JuliaInterpreter/src/interpret.jl:201 [inlined]
    [5] eval_rhs(recurse::Any, frame::Frame, node::Expr)
      @ JuliaInterpreter ~/.julia/dev/JuliaInterpreter/src/interpret.jl:400
    [6] step_expr!(recurse::Any, frame::Frame, node::Any, istoplevel::Bool)
      @ JuliaInterpreter ~/.julia/dev/JuliaInterpreter/src/interpret.jl:546
    [7] step_expr!(recurse::Any, frame::Frame, istoplevel::Bool)
      @ JuliaInterpreter ~/.julia/dev/JuliaInterpreter/src/interpret.jl:596
    [8] finish!(recurse::Any, frame::Frame, istoplevel::Bool)
      @ JuliaInterpreter ~/.julia/dev/JuliaInterpreter/src/commands.jl:14
    [9] finish_and_return!
      @ ~/.julia/dev/JuliaInterpreter/src/commands.jl:30 [inlined]
   [10] evaluate_call_recurse!(recurse::Any, frame::Frame, call_expr::Expr; enter_generated::Bool)
      @ JuliaInterpreter ~/.julia/dev/JuliaInterpreter/src/interpret.jl:240
   [11] evaluate_call_recurse!
      @ ~/.julia/dev/JuliaInterpreter/src/interpret.jl:201 [inlined]
   [12] eval_rhs(recurse::Any, frame::Frame, node::Expr)
      @ JuliaInterpreter ~/.julia/dev/JuliaInterpreter/src/interpret.jl:400
   [13] step_expr!(recurse::Any, frame::Frame, node::Any, istoplevel::Bool)
      @ JuliaInterpreter ~/.julia/dev/JuliaInterpreter/src/interpret.jl:541
   [14] step_expr!(recurse::Any, frame::Frame, istoplevel::Bool)
      @ JuliaInterpreter ~/.julia/dev/JuliaInterpreter/src/interpret.jl:596
   [15] finish!(recurse::Any, frame::Frame, istoplevel::Bool)
      @ JuliaInterpreter ~/.julia/dev/JuliaInterpreter/src/commands.jl:14
   [16] finish_and_return!
      @ ~/.julia/dev/JuliaInterpreter/src/commands.jl:30 [inlined]
   [17] finish_and_return!(frame::Frame, istoplevel::Bool)
      @ JuliaInterpreter ~/.julia/dev/JuliaInterpreter/src/commands.jl:34
   [18] macro expansion
      @ REPL[4]:3 [inlined]
   [19] macro expansion
      @ ~/src/julia-1/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
   [20] top-level scope
      @ REPL[4]:2
Test Summary: | Error  Total
include       |     1      1
ERROR: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
```

Do we need to remove more of those splats? I confess to not looking closely.

**Comment by pfitzseb** [comment]
IIUC we only want the `append_any(arargswrapped...)` for `_apply_iterate`, because that's where we handle the implied `iterate` call ourselves. So
```
diff --git a/bin/generate_builtins.jl b/bin/generate_builtins.jl
index 1b86054..40393ce 100644
--- a/bin/generate_builtins.jl
+++ b/bin/generate_builtins.jl
@@ -146,14 +146,13 @@ function maybe_evaluate_builtin(frame, call_expr, expand::Bool)
             print(io,
 """
     $head f === $fstr
-        argswrapped = getargs(args, frame)
+        args = getargs(args, frame)
         if !expand
-            return Some{Any}($fstr(argswrapped...))
+            return Some{Any}($fstr(args...))
         end
-        new_expr = Expr(:call, argswrapped[1])
-        popfirst!(argswrapped)
-        argsflat = append_any(argswrapped...)
-        for x in argsflat
+        new_expr = Expr(:call, args[1])
+        popfirst!(args)
+        for x in args
             push!(new_expr.args, (isa(x, Symbol) || isa(x, Expr) || isa(x, QuoteNode)) ? QuoteNode(x) : x)
         end
         return new_expr
diff --git a/src/builtins.jl b/src/builtins.jl
index 6160e80..599f660 100644
--- a/src/builtins.jl
+++ b/src/builtins.jl
@@ -52,38 +52,35 @@ function maybe_evaluate_builtin(frame, call_expr, expand::Bool)
             return Some{Any}(===(getargs(args, frame)...))
         end
     elseif f === Core._apply
-        argswrapped = getargs(args, frame)
+        args = getargs(args, frame)
         if !expand
-            return Some{Any}(Core._apply(argswrapped...))
+            return Some{Any}(Core._apply(args...))
         end
-        new_expr = Expr(:call, argswrapped[1])
-        popfirst!(argswrapped)
-        argsflat = append_any(argswrapped...)
-        for x in argsflat
+        new_expr = Expr(:call, args[1])
+        popfirst!(args)
+        for x in args
             push!(new_expr.args, (isa(x, Symbol) || isa(x, Expr) || isa(x, QuoteNode)) ? QuoteNode(x) : x)
         end
         return new_expr
     elseif @static isdefined(Core, :_call_latest) ? f === Core._call_latest : false
-        argswrapped = getargs(args, frame)
+        args = getargs(args, frame)
         if !expand
-            return Some{Any}(Core._call_latest(argswrapped...))
+            return Some{Any}(Core._call_latest(args...))
         end
-        new_expr = Expr(:call, argswrapped[1])
-        popfirst!(argswrapped)
-        argsflat = append_any(argswrapped)
-        for x in argsflat
+        new_expr = Expr(:call, args[1])
+        popfirst!(args)
+        for x in args
             push!(new_expr.args, (isa(x, Symbol) || isa(x, Expr) || isa(x, QuoteNode)) ? QuoteNode(x) : x)
         end
         return new_expr
     elseif @static isdefined(Core, :_apply_latest) ? f === Core._apply_latest : false
-        argswrapped = getargs(args, frame)
+        args = getargs(args, frame)
         if !expand
-            return Some{Any}(Core._apply_latest(argswrapped...))
+            return Some{Any}(Core._apply_latest(args...))
         end
-        new_expr = Expr(:call, argswrapped[1])
-        popfirst!(argswrapped)
-        argsflat = append_any(argswrapped...)
-        for x in argsflat
+        new_expr = Expr(:call, args[1])
+        popfirst!(args)
+        for x in args
             push!(new_expr.args, (isa(x, Symbol) || isa(x, Expr) || isa(x, QuoteNode)) ? QuoteNode(x) : x)
         end
         return new_expr
```
is probably correct, but unfortunately only the test added here actually hits any of that code.

**Comment by timholy** [comment]
Feel free to push that diff to this branch and I'll look into adding tests.

**Comment by pfitzseb** [comment]
Can we get this merged?

**Comment by KristofferC** [comment]
:+1:

**Review by aviatesk — APPROVED** [review]

**Pull request merged**
