### PR TITLE
More correctness fixes

### LINKED ISSUE #31: MWE of tuple test failure
This looks more isolated to JuliaInterpreter.
```
using JuliaInterpreter
ex = quote
    struct BitPerm_19352
        p::NTuple{8,UInt8}
        function BitPerm(p::NTuple{8,UInt8})
            new(p)
        end
        BitPerm_19352(xs::Vararg{Any,8}) = BitPerm(map(UInt8, xs))
    end
end
frame = JuliaInterpreter.prepare_toplevel(Main, ex)
JuliaInterpreter.finish_and_return!(JuliaStackFrame[], frame, true)
```
gives
```
ERROR: TypeError: in typeassert, expected Expr, got Array{Any,1}
Stacktrace:
 [1] eval_rhs(::Array{JuliaStackFrame,1}, ::JuliaStackFrame, ::Expr, ::JuliaInterpreter.JuliaProgramCounter) at /home/gunnar/.julia/dev/JuliaInterpreter/src/interpret.jl:307
 [2] _step_expr!(::Array{JuliaStackFrame,1}, ::JuliaStackFrame, ::Any, ::JuliaInterpreter.JuliaProgramCounter, ::Bool) at /home/gunnar/.julia/dev/JuliaInterpreter/src/interpret.jl:408
 [3] _step_expr!(::Array{JuliaStackFrame,1}, ::JuliaStackFrame, ::JuliaInterpreter.JuliaProgramCounter, ::Bool) at /home/gunnar/.julia/dev/JuliaInterpreter/src/interpret.jl:436
 [4] finish!(::Array{JuliaStackFrame,1}, ::JuliaStackFrame, ::JuliaInterpreter.JuliaProgramCounter, ::Bool) at /home/gunnar/.julia/dev/JuliaInterpreter/src/interpret.jl:479
 [5] finish_and_return!(::Array{JuliaStackFrame,1}, ::JuliaStackFrame, ::JuliaInterpreter.JuliaProgramCounter, ::Bool) at /home/gunnar/.julia/dev/JuliaInterpreter/src/interpret.jl:498
 [6] finish_and_return!(::Array{JuliaStackFrame,1}, ::JuliaStackFrame, ::Bool) at /home/gunnar/.julia/dev/JuliaInterpreter/src/interpret.jl:503
 [7] top-level scope at REPL[4]:1
```

### PR DESCRIPTION
**Pull request by timholy**
I discovered these while working on using this package to extract all method signatures from Base. Fixes #31 (though not enough to get the entire `tuple.jl` test running).

### CODE REVIEW

**Comment by KristofferC** [comment]
It seems this PR made running the julia tests on the stdlibs "worse" (at least they seemed to pass before this). An example is the Random stdlib which after this fails with:

```
"cglobal: first argument not a pointer or valid constant expression"), "", Ptr, (:__gmpz_clear, :libgmp))
```

**Comment by pfitzseb** [comment]
I'm also getting this locally on JuliaInterpreter's tests:
```
Main tests: Error During Test at /home/pfitzseb/.julia/dev/JuliaInterpreter/test/runtests.jl:4
  Got exception outside of a @test
  LoadError: TypeError: in cglobal: first argument not a pointer or valid constant expression, expected Ptr, got Tuple{Symbol,Symbol}
```
Went away after `pkg> build JuliaInterpreter` to re-generate builtins.jl, so maybe try that.

**Comment by KristofferC** [comment]
Yep, `build` did the trick. Thanks!

**Comment by timholy** [comment]
I should have thought to mention that in the OP, sorry about that. Glad you figured it out!

**Pull request merged**
