### PR TITLE
Adjust to upcoming Base Vararg change

### PR DESCRIPTION
**Pull request by Keno**

### CODE REVIEW

**Comment by timholy** [comment]
Thanks! Merge at will.

**Comment by timholy** [comment]
Now that the Vararg change is in, let's re-run CI here.

**Comment by timholy** [comment]
Looks like this will need some additional tweaks?

**Comment by aviatesk** [comment]
> Looks like this will need some additional tweaks?

the nightly failures seems to be those addressed by #449

**Comment by aviatesk** [comment]
It turns out we certainly need more tweaks: I just tried #449 with cherrypicking this branch, and got the following result:
```julia
JuliaInterpreter) pkg> test
     Testing JuliaInterpreter
Status `/private/var/folders/25/s2ggsb556lqfw0q9cflwnyfr0000gn/T/jl_5rLv4j/Project.toml`
  [da1fd8a2] CodeTracking v1.0.5
  [a93c6f00] DataFrames v0.21.8
  [aa1ae85d] JuliaInterpreter v0.8.6 `~/julia/packages/JuliaInterpreter`
  [70df011a] TableReader v0.4.0
  [48a634ad] Tensors v1.4.3
  [ade2ca70] Dates `@stdlib/Dates`
  [8ba89e20] Distributed `@stdlib/Distributed`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [a63ad114] Mmap `@stdlib/Mmap`
  [9a3f8284] Random `@stdlib/Random`
  [ea8e919c] SHA `@stdlib/SHA`
  [2f01184e] SparseArrays `@stdlib/SparseArrays`
  [8dfed614] Test `@stdlib/Test`
  [cf7118a7] UUIDs `@stdlib/UUIDs`
Status `/private/var/folders/25/s2ggsb556lqfw0q9cflwnyfr0000gn/T/jl_5rLv4j/Manifest.toml`
  [324d7699] CategoricalArrays v0.8.3
  [da1fd8a2] CodeTracking v1.0.5
  [ba30903b] CodecXz v0.7.0
  [944b1d66] CodecZlib v0.7.0
  [6b39b394] CodecZstd v0.7.0
  [bbf7d656] CommonSubexpressions v0.3.0
  [34da2185] Compat v3.25.0
  [9a962f9c] DataAPI v1.4.0
  [a93c6f00] DataFrames v0.21.8
  [864edb3b] DataStructures v0.18.8
  [e2d170a0] DataValueInterfaces v1.0.0
  [163ba53b] DiffResults v1.0.3
  [b552c78f] DiffRules v1.0.2
  [f6369f11] ForwardDiff v0.10.14
  [41ab1584] InvertedIndices v1.0.0
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.1.3
  [682c06a0] JSON v0.21.1
  [aa1ae85d] JuliaInterpreter v0.8.6 `~/julia/packages/JuliaInterpreter`
  [1914dd2f] MacroTools v0.5.6
  [e1d29d7a] Missings v0.4.4
  [77ba4419] NaNMath v0.3.5
  [bac558e1] OrderedCollections v1.3.2
  [69de0a69] Parsers v1.0.15
  [2dfb63ee] PooledArrays v0.5.3
  [189a3867] Reexport v0.2.0
  [fdea26ae] SIMD v3.2.1
  [a2af1166] SortingAlgorithms v0.3.1
  [276daf66] SpecialFunctions v1.1.0
  [90137ffa] StaticArrays v1.0.1
  [856f2bd8] StructTypes v1.2.1
  [70df011a] TableReader v0.4.0
  [3783bdb8] TableTraits v1.0.0
  [bd369af6] Tables v1.2.2
  [48a634ad] Tensors v1.4.3
  [3bb67fe8] TranscodingStreams v0.9.5
  [efe28fd5] OpenSpecFun_jll v0.5.3+4
  [ffd25f8a] XZ_jll v5.2.5+0
  [3161d3a3] Zstd_jll v1.4.5+2
  [0dad84c5] ArgTools `@stdlib/ArgTools`
  [56f22d72] Artifacts `@stdlib/Artifacts`
  [2a0f44e3] Base64 `@stdlib/Base64`
  [ade2ca70] Dates `@stdlib/Dates`
  [8bb1440f] DelimitedFiles `@stdlib/DelimitedFiles`
  [8ba89e20] Distributed `@stdlib/Distributed`
  [f43a241f] Downloads `@stdlib/Downloads`
  [9fa8497b] Future `@stdlib/Future`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [b27032c2] LibCURL `@stdlib/LibCURL`
  [76f85450] LibGit2 `@stdlib/LibGit2`
  [8f399da3] Libdl `@stdlib/Libdl`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [56ddb016] Logging `@stdlib/Logging`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [a63ad114] Mmap `@stdlib/Mmap`
  [ca575930] NetworkOptions `@stdlib/NetworkOptions`
  [44cfe95a] Pkg `@stdlib/Pkg`
  [de0858da] Printf `@stdlib/Printf`
  [3fa0cd96] REPL `@stdlib/REPL`
  [9a3f8284] Random `@stdlib/Random`
  [ea8e919c] SHA `@stdlib/SHA`
  [9e88b42a] Serialization `@stdlib/Serialization`
  [1a1011a3] SharedArrays `@stdlib/SharedArrays`
  [6462fe0b] Sockets `@stdlib/Sockets`
  [2f01184e] SparseArrays `@stdlib/SparseArrays`
  [10745b16] Statistics `@stdlib/Statistics`
  [fa267f1f] TOML `@stdlib/TOML`
  [a4e569a6] Tar `@stdlib/Tar`
  [8dfed614] Test `@stdlib/Test`
  [cf7118a7] UUIDs `@stdlib/UUIDs`
  [4ec0a83e] Unicode `@stdlib/Unicode`
  [e66e0078] CompilerSupportLibraries_jll `@stdlib/CompilerSupportLibraries_jll`
  [deac9b47] LibCURL_jll `@stdlib/LibCURL_jll`
  [29816b5a] LibSSH2_jll `@stdlib/LibSSH2_jll`
  [c8ffd9c3] MbedTLS_jll `@stdlib/MbedTLS_jll`
  [14a3606d] MozillaCACerts_jll `@stdlib/MozillaCACerts_jll`
  [83775a58] Zlib_jll `@stdlib/Zlib_jll`
  [8e850ede] nghttp2_jll `@stdlib/nghttp2_jll`
     Testing Running tests...
Skipping Base.active_repl
Skipping Base.active_repl_backend
Skipping Base.active_repl
Skipping Base.active_repl_backend
Main tests: Error During Test at /Users/aviatesk/julia/packages/JuliaInterpreter/test/interpret.jl:106
  Test threw exception
  Expression: #= /Users/aviatesk/julia/packages/JuliaInterpreter/test/interpret.jl:106 =# @interpret(Vararg.body.body.name) === Vararg.body.body.name
  type TypeofVararg has no field body
  Stacktrace:
   [1] getproperty(x::Core.TypeofVararg, f::Symbol)
     @ Base ./Base.jl:33
   [2] top-level scope
     @ ~/julia/packages/JuliaInterpreter/src/construct.jl:767
   [3] include(fname::String)
     @ Base.MainInclude ./client.jl:444
   [4] macro expansion
     @ ~/julia/packages/JuliaInterpreter/test/runtests.jl:14 [inlined]
   [5] macro expansion
     @ ~/julia/julia/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1148 [inlined]
   [6] top-level scope
     @ ~/julia/packages/JuliaInterpreter/test/runtests.jl:13
Main tests: Error During Test at /Users/aviatesk/julia/packages/JuliaInterpreter/test/interpret.jl:109
  Test threw exception
  Expression: JuliaInterpreter.finish_and_return!(frame, true) === Vararg.body.body.name
  type TypeofVararg has no field body
  Stacktrace:
    [1] getproperty(x::Core.TypeofVararg, f::Symbol)
      @ Base ./Base.jl:33
    [2] get_call_framecode(fargs::Vector{Any}, parentframe::JuliaInterpreter.FrameCode, idx::Int64; enter_generated::Bool)
      @ JuliaInterpreter ~/julia/packages/JuliaInterpreter/src/localmethtable.jl:64
    [3] evaluate_call_recurse!(recurse::Any, frame::Frame, call_expr::Expr; enter_generated::Bool)
      @ JuliaInterpreter ~/julia/packages/JuliaInterpreter/src/interpret.jl:224
    [4] evaluate_call_recurse!
      @ ~/julia/packages/JuliaInterpreter/src/interpret.jl:201 [inlined]
    [5] eval_rhs(recurse::Any, frame::Frame, node::Expr)
      @ JuliaInterpreter ~/julia/packages/JuliaInterpreter/src/interpret.jl:394
    [6] step_expr!(recurse::Any, frame::Frame, node::Any, istoplevel::Bool)
      @ JuliaInterpreter ~/julia/packages/JuliaInterpreter/src/interpret.jl:532
    [7] step_expr!
      @ ~/julia/packages/JuliaInterpreter/src/interpret.jl:587 [inlined]
    [8] finish!(recurse::Any, frame::Frame, istoplevel::Bool)
      @ JuliaInterpreter ~/julia/packages/JuliaInterpreter/src/commands.jl:14
    [9] finish_and_return!
      @ ~/julia/packages/JuliaInterpreter/src/commands.jl:29 [inlined]
   [10] finish_and_return!(frame::Frame, istoplevel::Bool)
      @ JuliaInterpreter ~/julia/packages/JuliaInterpreter/src/commands.jl:33
   [11] top-level scope
      @ ~/julia/packages/JuliaInterpreter/test/interpret.jl:109
   [12] include(fname::String)
      @ Base.MainInclude ./client.jl:444
   [13] macro expansion
      @ ~/julia/packages/JuliaInterpreter/test/runtests.jl:14 [inlined]
   [14] macro expansion
      @ ~/julia/julia/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1148 [inlined]
   [15] top-level scope
      @ ~/julia/packages/JuliaInterpreter/test/runtests.jl:13
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).┌ Warning: Assignment to `frame` in soft scope is ambiguous because a global variable by the same name exists: `frame` will be treated as a new local. Disambiguate by using `local frame` to suppress this warning or `global frame` to assign to the existing global variable.
└ @ ~/julia/packages/JuliaInterpreter/test/interpret.jl:478
┌ Warning: Assignment to `frame` in soft scope is ambiguous because a global variable by the same name exists: `frame` will be treated as a new local. Disambiguate by using `local frame` to suppress this warning or `global frame` to assign to the existing global variable.
└ @ ~/julia/packages/JuliaInterpreter/test/interpret.jl:506
WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).[ Info: logging macros
┌ Warning: Assignment to `frame` in soft scope is ambiguous because a global variable by the same name exists: `frame` will be treated as a new local. Disambiguate by using `local frame` to suppress this warning or `global frame` to assign to the existing global variable.
└ @ ~/julia/packages/JuliaInterpreter/test/toplevel.jl:310
WARNING: Method definition inner(Any) in module Main at /Users/aviatesk/julia/packages/JuliaInterpreter/test/breakpoints.jl:97 overwritten at /Users/aviatesk/julia/packages/JuliaInterpreter/test/breakpoints.jl:154.
WARNING: Method definition f22() in module Main at /Users/aviatesk/julia/packages/JuliaInterpreter/test/debug.jl:97 overwritten at /Users/aviatesk/julia/packages/JuliaInterpreter/test/debug.jl:99.
Test Summary:                                            | Pass  Error  Broken  Total
Main tests                                               |  686      2       2    690
  core                                                   |    5                     5
  Some tests                                             |    1                     1
  locals                                                 |   14                    14
  getfield replacements                                  |    4                     4
  vararg handling                                        |    2                     2
  issue 285                                              |    1                     1
  issue 351                                              |    1                     1
  invoke                                                 |    2                     2
  constructor locals                                     |    1                     1
  Basics                                                 |   13                    13
  toplevel                                               |  120                   120
  Namespace                                              |    2                     2
  Namespace stdlibs                                      |    1                     1
  issue #15703                                           |    1                     1
  Enum                                                   |    1                     1
  Anonymous functions                                    |    4                     4
  Docstrings                                             |    4                     4
  Self referential                                       |    1                     1
  Non-frames                                             |    1                     1
  LOAD_PATH and modules                                  |    1                     1
  `used` for abstract types                              |    1                     1
  Recursive type definitions                             |    1                     1
  Nested references in type definitions                  |    1                     1
  Issue #427                                             |    7                     7
  Abort                                                  |    4                     4
  evaluate_limited                                       |   14                    14
  Breakpoints                                            |   47              1     48
  toggling                                               |    5                     5
  breakpoint in stdlibs by path                          |    4                     4
  breakpoint in Base by path                             |    4                     4
  breakpoint by type                                     |    1                     1
  hooks                                                  |    9                     9
  toplevel breakpoints                                   |    6                     6
  Basics                                                 |  177                   177
  until                                                  |    4                     4
  generated                                              |   17                    17
  Optional arguments                                     |    2                     2
  Keyword arguments                                      |    4                     4
  Optional + keyword wrappers                            |   13                    13
  Macros                                                 |    1                     1
  Quoting                                                |    2                     2
  Varargs                                                |    3                     3
  ASTI#17                                                |   17                    17
  Exceptions                                             |   11                    11
  breakpoints                                            |    9                     9
  invoke                                                 |    2                     2
  invokelatest                                           |    2                     2
  Issue #178                                             |    2                     2
  Stepping over kwfunc preparation                       |    5                     5
  interaction of :n with kw functions                    |    2                     2
  stepping through kwprep after stepping through wrapper |    1                     1
  si should not step through wrappers or kwprep          |    1                     1
  breakpoints hit during wrapper step through            |    1                     1
  preservation of stack when throwing to toplevel        |    1                     1
  breakpoint in next line                                |    1                     1
ERROR: LoadError: Some tests did not pass: 686 passed, 0 failed, 2 errored, 2 broken.
in expression starting at /Users/aviatesk/julia/packages/JuliaInterpreter/test/runtests.jl:12
ERROR: Package JuliaInterpreter errored during testing
```

**Comment by timholy** [comment]
Worth pointing out that since Revise depends on JuliaInterpreter, a lot of development on julia-master might be broken until this gets fixed.

**Comment by simeonschaub** [comment]
> It turns out we certainly need more tweaks (in test code, I guess).

I think it's just a matter of disabling two tests that directly test implementation details of `Vararg`. All tests pass for me with this patch:
```diff
diff --git a/test/interpret.jl b/test/interpret.jl
index 9b87ef9..b6faa0a 100644
--- a/test/interpret.jl
+++ b/test/interpret.jl
@@ -103,10 +103,14 @@ end
 @test @interpret(10.0^4) == 10.0^4
 # issue #6
 @test @interpret(Array.body.body.name) === Array.body.body.name
-@test @interpret(Vararg.body.body.name) === Vararg.body.body.name
+if Vararg isa DataType
+    @test @interpret(Vararg.body.body.name) === Vararg.body.body.name
+end
 @test !JuliaInterpreter.is_vararg_type(Union{})
-frame = Frame(Main, :(Vararg.body.body.name))
-@test JuliaInterpreter.finish_and_return!(frame, true) === Vararg.body.body.name
+if Vararg isa DataType
+    frame = Frame(Main, :(Vararg.body.body.name))
+    @test JuliaInterpreter.finish_and_return!(frame, true) === Vararg.body.body.name
+end
 frame = Frame(Base, :(Union{AbstractChar,Tuple{Vararg{<:AbstractChar}},AbstractVector{<:AbstractChar},Set{<:AbstractChar}}))
 @test JuliaInterpreter.finish_and_return!(frame, true) isa Union
```
Should I just make one PR with commits from here and #449, which can then be rebased on master, or would it be better to keep those as separate PRs?

**Comment by timholy** [comment]
Thanks for looking, I hadn't taken the time to check in detail.

Let's keep the PRs separate and tolerate the failure when we merge.

**Pull request closed without merging**
