### PR TITLE
fix at-ccall?

### PR DESCRIPTION
**Pull request by pfitzseb**
Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/433.

I feel like this is probably not the correct fix, but it works, so... ¯\\\_(ツ)\_/¯

### CODE REVIEW

**Comment by timholy** [comment]
I've not followed `@ccall`, but note the test failures that prevent this from being merged.

**Comment by pfitzseb** [comment]
So I think this actually works now, instead of just accidentally for the one test function I had.

**Comment by pfitzseb** [comment]
Remaining test errors are unrelated.

**Comment by timholy** [comment]
Thanks!

**Pull request merged**
