### PR TITLE
very slight support for `OpaqueClosure`s

### PR DESCRIPTION
**Pull request by oscardssmith**
this will prevent them from crashing, but will not allow stepping into them.

### CODE REVIEW

**Comment by pfitzseb** [comment]
Will also need to be added to https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/master/bin/generate_builtins.jl.

**Comment by KristofferC** [comment]
Also, a test would be good.

**Comment by oscardssmith** [comment]
does this look right?

**Comment by oscardssmith** [comment]
@pfitzseb thanks for fixing the broken-ness!

**Review by pfitzseb — APPROVED** [review]

**Pull request merged**
